### PR TITLE
Restore support for pseudo handles

### PR DESCRIPTION
**Pull request by m417z**
As @injertao noticed [here](https://github.com/rwfpl/rewolf-wow64ext/pull/21#issuecomment-1176092665), my previous change broke support for pseudo handles.

### CODE REVIEW

**Comment by therealdreg** [comment]
btw @m417z

**pointer <--> integer** is implementation defined, So take a look: __sptr, __uptr:

https://docs.microsoft.com/en-us/cpp/cpp/sptr-uptr

**Comment by m417z** [comment]
In this case, the pointer is first converted to an integer of the same size, so there's no pointer to integer (sign or zero) extension. I think it's OK.

**Comment by therealdreg** [comment]
An example:

```
    void* ptr = 0xFFFFFFFF;

    int64_t val = ptr; // in VC val = 0xffffffffffffffff

    int64_t val2 = (int* __ptr32 __uptr) ptr; // in VC val2 = 0x00000000ffffffff

    int64_t val3 = (int* __ptr32 __sptr) ptr; // in VC val2 = 0xffffffffffffffff
```

**Comment by therealdreg** [comment]
@rwfpl can you merge this fix please?

**Review by rwfpl — APPROVED** [review]

**Pull request merged**
